# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [1]:
import numpy as np

In [3]:
array1 = np.arange(10, 101)
print("Array original:")
print(array1)

Array original:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [4]:
array1_invertido = np.flip(array1)
print("\nArray invertido:")
print(array1_invertido)


Array invertido:
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]


In [5]:
array2 = np.arange(9).reshape(3,3)
print("\nArray 3x3:")
print(array2)


Array 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
array_identidade = np.eye(6)
print("\nArray identidade 6x6:")
print(array_identidade)


Array identidade 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [7]:
array_aleatorio = np.random.rand(3,3,3)
print("\nArray 3x3x3 aleatório:")
print(array_aleatorio)


Array 3x3x3 aleatório:
[[[0.37224117 0.56706491 0.3226324 ]
  [0.62399295 0.22135292 0.99516951]
  [0.08614152 0.29026438 0.63905953]]

 [[0.51983535 0.74018081 0.99172474]
  [0.47903113 0.18612574 0.69538373]
  [0.05755033 0.09379918 0.79910452]]

 [[0.23873456 0.72782005 0.16988154]
  [0.04796199 0.14053808 0.75023893]
  [0.07189319 0.08166422 0.55863308]]]


In [8]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
print("\nArray A:")
print(A)
print("\nArray B:")
print(B)
print("\nOs arrays A e B são iguais?")
print(np.array_equal(A, B))


Array A:
[[0.81784495 0.82565719 0.78182082]
 [0.54433934 0.17188066 0.82660553]
 [0.61211866 0.02337056 0.89843481]]

Array B:
[[0.59020494 0.85433246 0.92448818]
 [0.46859949 0.07135503 0.45662633]
 [0.85724242 0.27152107 0.55420229]]

Os arrays A e B são iguais?
False


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [9]:
dolares = np.random.randint(1, 1001, 100)
print("\nArray de dólares:")
print(dolares)


Array de dólares:
[757 338 370 132 728 167 661 724 675 957 102  85 266 479 385 658  15  68
 770 347 936 686 669  32 662 422 839 922 689 774 310 628 657 124 664 666
 656  60 540 282 522 596 140 184 870 884 178 456 178 446 883 926 151 647
 805 294 823 110 485 303 704 857 295 185 914 670  63 496 326 946 652 193
 652 626 368 245 568 265 960 633 365 766 938 550 550 933 192 257 672 384
 339  17 528 153 129 970 393 308 131  13]


In [10]:
conversao = 0.874413
euros = dolares * conversao
euros = np.round(euros, 2)
print("\nArray de euros:")
print(euros)


Array de euros:
[661.93 295.55 323.53 115.42 636.57 146.03 577.99 633.08 590.23 836.81
  89.19  74.33 232.59 418.84 336.65 575.36  13.12  59.46 673.3  303.42
 818.45 599.85 584.98  27.98 578.86 369.   733.63 806.21 602.47 676.8
 271.07 549.13 574.49 108.43 580.61 582.36 573.61  52.46 472.18 246.58
 456.44 521.15 122.42 160.89 760.74 772.98 155.65 398.73 155.65 389.99
 772.11 809.71 132.04 565.75 703.9  257.08 719.64  96.19 424.09 264.95
 615.59 749.37 257.95 161.77 799.21 585.86  55.09 433.71 285.06 827.19
 570.12 168.76 570.12 547.38 321.78 214.23 496.67 231.72 839.44 553.5
 319.16 669.8  820.2  480.93 480.93 815.83 167.89 224.72 587.61 335.77
 296.43  14.87 461.69 133.79 112.8  848.18 343.64 269.32 114.55  11.37]


**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [11]:
import pandas as pd

In [12]:
df_titulos = pd.read_csv('05_05_imdb_titulos.csv')
df_elenco = pd.read_csv('05_05_imdb_elenco.csv')

In [13]:
print("5 primeiros registros do dataframe de títulos:")
print(df_titulos.head())

5 primeiros registros do dataframe de títulos:
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989


In [14]:
print("\n5 primeiros registros do dataframe de elenco:")
print(df_elenco.head())


5 primeiros registros do dataframe de elenco:
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN


In [15]:
print("\n5 primeiros registros do dataframe de elenco:")
print(df_elenco.head())


5 primeiros registros do dataframe de elenco:
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN


In [19]:
print(df_titulos.sort_values('year').head())

                                                    title  year
13229                                          Miss Jerry  1894
103233                                 The Startled Lover  1898
133020     Reproduction of the Corbett and Jeffries Fight  1899
51528                                Family Troubles (II)  1900
195127  Pierrot's Problem, or How to Make a Fat Wife O...  1900


In [21]:
dracula_filmes = df_titulos[df_titulos['title'].str.contains('Drácula', case=False)]
print("\nFilmes que contém a palavra 'Drácula': ", len(dracula_filmes))


Filmes que contém a palavra 'Drácula':  0


In [22]:
print("\n10 títulos mais comuns:")
print(df_titulos['title'].value_counts().head(10))


10 títulos mais comuns:
Hamlet                  19
Carmen                  16
Macbeth                 15
Maya                    11
The Outsider            11
Hero                    11
Othello                 11
The Three Musketeers    11
Anna                    10
Vengeance               10
Name: title, dtype: int64


In [23]:
primeiro_romeo_juliet = df_titulos[df_titulos['title'] == 'Romeo and Juliet'].sort_values('year').head(1)
print("\nPrimeiro filme chamado 'Romeo and Juliet':")
print(primeiro_romeo_juliet)


Primeiro filme chamado 'Romeo and Juliet':
                   title  year
124702  Romeo and Juliet  1916


In [24]:
exorcist_filmes = df_titulos[df_titulos['title'].str.contains('Exorcist', case=False)].sort_values('year')
print("\nFilmes que contém a palavra 'Exorcist', ordenados do mais antigo ao mais recente:")
print(exorcist_filmes)


Filmes que contém a palavra 'Exorcist', ordenados do mais antigo ao mais recente:
                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
51101                            Bad Exorcists  2015
151850                              Exorcistas  2015
60700           

In [25]:
filmes_1950 = len(df_titulos[df_titulos['year'] == 1950])
print("\nNúmero de filmes feitos no ano de 1950: ", filmes_1950)


Número de filmes feitos no ano de 1950:  1081


In [26]:
filmes_1950_1959 = len(df_titulos[(df_titulos['year'] >= 1950) & (df_titulos['year'] <= 1959)])
print("\nNúmero de filmes feitos de 1950 a 1959: ", filmes_1950_1959)


Número de filmes feitos de 1950 a 1959:  12606


In [28]:
trilogia_godfather = df_elenco[df_elenco['title'].str.contains('The Godfather', case=False)].groupby('character').size()
print("\nPapéis da trilogia 'The Godfather':")
print(trilogia_godfather)


Papéis da trilogia 'The Godfather':
character
Al Neri                            2
Albert Volpe                       1
Alfio in 'Cavalleria Rusticana'    2
Anthony 'The Ant' Squigliaro       1
Anthony Corleone                   1
                                  ..
Young Hyman Roth                   1
Young Mama Corleone                1
Young Tessio                       1
Young priest                       1
Zasa's Bodyguard                   1
Length: 262, dtype: int64


In [40]:
elenco_dracula_1958 = df_elenco[(df_elenco['title'] == 'Dracula') & (df_elenco['year'] == 1958)].sort_values('n')
print("\nElenco completo do filme 'Drácula' de 1958, ordenado pela classificação:")
print(elenco_dracula_1958)


Elenco completo do filme 'Drácula' de 1958, ordenado pela classificação:
           title  year                   name     type  \
485197   Dracula  1958          Peter Cushing    actor   
1242307  Dracula  1958        Christopher Lee    actor   
1242308  Dracula  1958        Christopher Lee    actor   
822398   Dracula  1958          Michael Gough    actor   
3410427  Dracula  1958      Melissa Stribling  actress   
3069196  Dracula  1958            Carol Marsh  actress   
2677557  Dracula  1958            Olga Dickie  actress   
2220986  Dracula  1958        John Van Eyssen    actor   
2777216  Dracula  1958          Valerie Gaunt  actress   
2731182  Dracula  1958            Janina Faye  actress   
2444220  Dracula  1958         Barbara Archer  actress   
1285506  Dracula  1958     Charles Lloyd Pack    actor   
1453367  Dracula  1958         George Merritt    actor   
2357769  Dracula  1958      George Woodbridge    actor   
171732   Dracula  1958          George Benson    actor  

In [41]:
bruce_wayne_papeis = df_elenco[df_elenco['character'].str.contains('Bruce Wayne', case=False)].shape[0]
print("\nNúmero de papéis que Bruce Wayne teve como protagonista: ", bruce_wayne_papeis)


Número de papéis que Bruce Wayne teve como protagonista:  49


In [43]:
de_niro_papeis = df_elenco[df_elenco['character'] == 'Robert De Niro'].shape[0]
print("\nNúmero de papéis de Robert De Niro na sua carreira: ", de_niro_papeis)


Número de papéis de Robert De Niro na sua carreira:  3


In [45]:
heston_60s = df_elenco[(df_elenco['name'] == 'Charlton Heston') & (df_elenco['n'] == 1) & (df_elenco['year'] >= 1960) & (df_elenco['year'] <= 1969)].sort_values('year', ascending=False)
print("\nPapéis como protagonista de Charlton Heston na década de 60:")



Papéis como protagonista de Charlton Heston na década de 60:


In [46]:
papeis_atores_50s = df_elenco[(df_elenco['n'] == 1) & (df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959) & (df_elenco['type'] == 'actor')].shape[0]
print("\nNúmero de papéis para atores na década de 50: ", papeis_atores_50s)


Número de papéis para atores na década de 50:  6565


In [48]:
papeis_atrizes_50s = df_elenco[(df_elenco['n'] == 1) & (df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959) & (df_elenco['type'] == 'actress')].shape[0]
print("Número de papéis para atrizes na década de 50: ", papeis_atrizes_50s)


Número de papéis para atrizes na década de 50:  2942
